#+OPTIONS: toc: nil
* dotfiles
This repo is supposed to a hub for all my different configuration files and 
useful scritps.
** install-arch.sh
*** Intro
This is a simple installation script made for Arch Linux. After downloading and 
reinstalling Arch on various systems and virtual machines I came to the 
conclusion that a simple script, using my standard configuration, would not
be that bad.

Feel free to use it if you feel like it can be helpful in any way
*** Getting started
There is not much to be said here. You can get the latest version of the script 
using a program like =wget= or =curl=

Example using wget
#+BEGIN_SRC sh
wget install-arch.cjiq.tk -O install-arch.sh && chmod +x install-arch.sh
#+END_SRC sh


Example using curl
#+BEGIN_SRC sh
curl -L -o install-arch.sh install-arch.cjiq.tk && chmod +x install-arch.sh
#+END_SRC sh

Run script by executing
#+BEGIN_SRC sh
./install-arch.sh
#+END_SRC sh

notice: install-arch.cjiq.tk just redirects you to the file found at Github.
** Disclaimer
I will not take any resposability if any of my scritps causes any trouble. 
Use them at your own risk. 
** License
MIT
