#!/usr/bin/bash

MAX=1000
MIN=1


CURRENT=`cat /sys/class/backlight/intel_backlight/brightness`
echo $(($CURRENT/10))
if [ -n "$1" ]; then
	DEM=$(set -f; echo $1)*10
	CURRENT=$(($CURRENT+$DEM))
	if (( $CURRENT < $MIN )); then
		CURRENT=$MIN
	fi
	if (( $CURRENT > $MAX )); then
		CURRENT=$MAX
	fi
	`tee /sys/class/backlight/intel_backlight/brightness <<< $CURRENT` > /dev/null 2>&1
fi
