#!/bin/bash

xrandr --auto
sleep 0.05
xrandr --output DP1-1 --mode 1600x1200
sleep 0.05
xrandr --output DP1-2 --mode 1600x1200
sleep 0.05
xrandr --output DP1-3 --mode 1600x1200
sleep 0.05
xrandr --output eDP1 --mode 1920x1080 --output DP1-1 --mode 1920x1200 --right-of eDP1 --output DP1-2 --mode 1920x1200 --right-of DP1-1
